#### general settings
name: Freq
train_type: CLS
gpu_ids: [2]

#### datasets
data:
  name: "CIFAR100"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_CIFAR100/"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### Model settings
model:
  name: "LeNet"
  layer_type: Freq

  in_channels: 3
  out_channels: 100

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 1000
  batch_size: 128
  train_size: 1

  loss: "CE"

#### Logging
logging:
  mode: online # disabled
  tags: [
      "CIFAR100",
      "CLS",
      "LeNet",
      "Frequentist"
    ]